### ISSUE TITLE
Some suggestion and known bugs

### ISSUE THREAD

**Issue by BusyStudent** [syoyo/nanovg-nanort#3]
## Memory leaks on free_texture
My valgrind detected memory leaks on rtnvg__deleteTexture

```cpp
    if (rt->textures[i].id == id) {
      if (rt->textures[i].tex != 0 &&
          (rt->textures[i].flags & NVG_IMAGE_NODELETE) == 0) {
        free(rt->textures[i].data);
        // glDeleteTextures(1, &rt->textures[i].tex);
      }
}

```
The tex is always be inited in 0
It will cause memory leaks
It should be 

```cpp
    if (rt->textures[i].id == id) {
      if ((rt->textures[i].flags & NVG_IMAGE_NODELETE) == 0) {
        free(rt->textures[i].data);
        // glDeleteTextures(1, &rt->textures[i].tex);
      }
}
```

## Current version of nanovg could not be compiled in C++17
   Because std::unary_function is removed in C++17
## on newest nanovg,rtnvg__renderTriangles has one extra param fringe
It shoud be 
```cpp
static void rtnvg__renderTriangles(void *uptr, NVGpaint *paint,
                                   NVGcompositeOperationState compositeOperation,
                                   NVGscissor *scissor, const NVGvertex *verts,
                                   int nverts,float fringe) {
  // printf("renderTriangles\n");
  RTNVGcontext *rt = (RTNVGcontext *)uptr;
  RTNVGcall *call = rtnvg__allocCall(rt);
	@@ -2367,7 +2194,7 @@ static void rtnvg__renderTriangles(void *uptr, NVGpaint *paint,
  if (call->uniformOffset == -1)
    goto error;
  frag = nvg__fragUniformPtr(rt, call->uniformOffset);
  rtnvg__convertPaint(rt, frag, paint, scissor, 1.0f, fringe, -1.0f);
  frag->type = NSVG_SHADER_IMG;
  //.....
}
```
## Run too slow
  the nanovg-rt run too slow,Only draw a circle or a curve will spend a lot of time,
  could you optimze it?
## Add a method to resize framebuffer
  like nvgResizeFrameBufferRT is a good choice

**Comment by syoyo** [comment]
Could you send PR?

For the speed, its a software raytracing so slow and no room for the optimization.

**Comment by BusyStudent** [comment]
Yes,I have fix memory leaks on my repo,but i didnot known how to port it to newest nanort
#4
